with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
packages:
  github.com/dmitastr/itk_academy_wallet_service/internal/domain/balance/service:
    interfaces:
      IWalletService:
  github.com/dmitastr/itk_academy_wallet_service/internal/repository/datasource/balance:
    interfaces:
      IDatasource: