// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/dmitastr/itk_academy_wallet_service/internal/domain/balance/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IWalletService is an autogenerated mock type for the IWalletService type
type IWalletService struct {
	mock.Mock
}

type IWalletService_Expecter struct {
	mock *mock.Mock
}

func (_m *IWalletService) EXPECT() *IWalletService_Expecter {
	return &IWalletService_Expecter{mock: &_m.Mock}
}

// AddDeposit provides a mock function with given fields: ctx, walletIncrement
func (_m *IWalletService) AddTransaction(ctx context.Context, walletIncrement *models.WalletIncrement) error {
	ret := _m.Called(ctx, walletIncrement)

	if len(ret) == 0 {
		panic("no return value specified for AddTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.WalletIncrement) error); ok {
		r0 = rf(ctx, walletIncrement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IWalletService_AddDeposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTransaction'
type IWalletService_AddDeposit_Call struct {
	*mock.Call
}

// AddDeposit is a helper method to define mock.On call
//   - ctx context.Context
//   - walletIncrement *models.WalletIncrement
func (_e *IWalletService_Expecter) AddDeposit(ctx interface{}, walletIncrement interface{}) *IWalletService_AddDeposit_Call {
	return &IWalletService_AddDeposit_Call{Call: _e.mock.On("AddTransaction", ctx, walletIncrement)}
}

func (_c *IWalletService_AddDeposit_Call) Run(run func(ctx context.Context, walletIncrement *models.WalletIncrement)) *IWalletService_AddDeposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.WalletIncrement))
	})
	return _c
}

func (_c *IWalletService_AddDeposit_Call) Return(_a0 error) *IWalletService_AddDeposit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IWalletService_AddDeposit_Call) RunAndReturn(run func(context.Context, *models.WalletIncrement) error) *IWalletService_AddDeposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function with given fields: ctx, walletID
func (_m *IWalletService) GetBalance(ctx context.Context, walletID uuid.UUID) (*models.WalletBalance, error) {
	ret := _m.Called(ctx, walletID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *models.WalletBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.WalletBalance, error)); ok {
		return rf(ctx, walletID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.WalletBalance); ok {
		r0 = rf(ctx, walletID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WalletBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IWalletService_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type IWalletService_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID uuid.UUID
func (_e *IWalletService_Expecter) GetBalance(ctx interface{}, walletID interface{}) *IWalletService_GetBalance_Call {
	return &IWalletService_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, walletID)}
}

func (_c *IWalletService_GetBalance_Call) Run(run func(ctx context.Context, walletID uuid.UUID)) *IWalletService_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *IWalletService_GetBalance_Call) Return(_a0 *models.WalletBalance, _a1 error) *IWalletService_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IWalletService_GetBalance_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.WalletBalance, error)) *IWalletService_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewIWalletService creates a new instance of IWalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IWalletService {
	mock := &IWalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
