// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/dmitastr/itk_academy_wallet_service/internal/domain/balance/models"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// IDatasource is an autogenerated mock type for the IDatasource type
type IDatasource struct {
	mock.Mock
}

type IDatasource_Expecter struct {
	mock *mock.Mock
}

func (_m *IDatasource) EXPECT() *IDatasource_Expecter {
	return &IDatasource_Expecter{mock: &_m.Mock}
}

// AddDeposit provides a mock function with given fields: ctx, increment
func (_m *IDatasource) AddDeposit(ctx context.Context, increment *models.WalletIncrement) error {
	ret := _m.Called(ctx, increment)

	if len(ret) == 0 {
		panic("no return value specified for AddDeposit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.WalletIncrement) error); ok {
		r0 = rf(ctx, increment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IDatasource_AddDeposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDeposit'
type IDatasource_AddDeposit_Call struct {
	*mock.Call
}

// AddDeposit is a helper method to define mock.On call
//   - ctx context.Context
//   - increment *models.WalletIncrement
func (_e *IDatasource_Expecter) AddDeposit(ctx interface{}, increment interface{}) *IDatasource_AddDeposit_Call {
	return &IDatasource_AddDeposit_Call{Call: _e.mock.On("AddDeposit", ctx, increment)}
}

func (_c *IDatasource_AddDeposit_Call) Run(run func(ctx context.Context, increment *models.WalletIncrement)) *IDatasource_AddDeposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.WalletIncrement))
	})
	return _c
}

func (_c *IDatasource_AddDeposit_Call) Return(_a0 error) *IDatasource_AddDeposit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDatasource_AddDeposit_Call) RunAndReturn(run func(context.Context, *models.WalletIncrement) error) *IDatasource_AddDeposit_Call {
	_c.Call.Return(run)
	return _c
}

// AddWithdrawal provides a mock function with given fields: ctx, increment
func (_m *IDatasource) AddWithdrawal(ctx context.Context, increment *models.WalletIncrement) error {
	ret := _m.Called(ctx, increment)

	if len(ret) == 0 {
		panic("no return value specified for AddWithdrawal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.WalletIncrement) error); ok {
		r0 = rf(ctx, increment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IDatasource_AddWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWithdrawal'
type IDatasource_AddWithdrawal_Call struct {
	*mock.Call
}

// AddWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - increment *models.WalletIncrement
func (_e *IDatasource_Expecter) AddWithdrawal(ctx interface{}, increment interface{}) *IDatasource_AddWithdrawal_Call {
	return &IDatasource_AddWithdrawal_Call{Call: _e.mock.On("AddWithdrawal", ctx, increment)}
}

func (_c *IDatasource_AddWithdrawal_Call) Run(run func(ctx context.Context, increment *models.WalletIncrement)) *IDatasource_AddWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.WalletIncrement))
	})
	return _c
}

func (_c *IDatasource_AddWithdrawal_Call) Return(_a0 error) *IDatasource_AddWithdrawal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDatasource_AddWithdrawal_Call) RunAndReturn(run func(context.Context, *models.WalletIncrement) error) *IDatasource_AddWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function with given fields: ctx, walletID
func (_m *IDatasource) GetBalance(ctx context.Context, walletID uuid.UUID) (*models.WalletBalance, error) {
	ret := _m.Called(ctx, walletID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *models.WalletBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.WalletBalance, error)); ok {
		return rf(ctx, walletID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.WalletBalance); ok {
		r0 = rf(ctx, walletID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WalletBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IDatasource_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type IDatasource_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID uuid.UUID
func (_e *IDatasource_Expecter) GetBalance(ctx interface{}, walletID interface{}) *IDatasource_GetBalance_Call {
	return &IDatasource_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, walletID)}
}

func (_c *IDatasource_GetBalance_Call) Run(run func(ctx context.Context, walletID uuid.UUID)) *IDatasource_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *IDatasource_GetBalance_Call) Return(_a0 *models.WalletBalance, _a1 error) *IDatasource_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IDatasource_GetBalance_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.WalletBalance, error)) *IDatasource_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewIDatasource creates a new instance of IDatasource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDatasource(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDatasource {
	mock := &IDatasource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
